version: "3.8"

services:
    flask_backend:
      container_name: flask_backend
      build: 
        context: ./backend
        dockerfile: Dockerfile
      ports:
        - "5500:5500"
      volumes:
        - ./backend:/code
      restart: always

    react_frontend:
        container_name: react_frontend
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
        volumes:
            - ./frontend:/usr/src/app
            # use npm instead of yarn
        command: sh -c "npm rebuild esbuild && yarn dev"
        restart: always

    mysql:
      container_name: database
      image: mysql:latest
      ports:
        - "3306:3306"
      volumes:
        - ./database:/docker-entrypoint-initdb.d/:ro
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: ColocApp

    phpmyadmin:
      container_name: database_admin
      image: phpmyadmin/phpmyadmin
      ports:
        - "8080:80"
      restart: always
      environment:
        PMA_HOST: mysql
        PMA_PORT: 3306
        PMA_USER: root
        PMA_PASSWORD: password
    