// Dashboard Constants for redux actions

// GET DASHBOARD Constants
export const GET_DASHBOARD_REQUEST = 'GET_DASHBOARD_REQUEST';
export const GET_DASHBOARD_SUCCESS = 'GET_DASHBOARD_SUCCESS';
export const GET_DASHBOARD_FAIL = 'GET_DASHBOARD_FAIL';

// CREATE DASHBOARD Constants
export const CREATE_DASHBOARD_REQUEST = 'CREATE_DASHBOARD_REQUEST';
export const CREATE_DASHBOARD_SUCCESS = 'CREATE_DASHBOARD_SUCCESS';
export const CREATE_DASHBOARD_FAIL = 'CREATE_DASHBOARD_FAIL';

// UPDATE DASHBOARD Constants
export const UPDATE_DASHBOARD_REQUEST = 'UPDATE_DASHBOARD_REQUEST';
export const UPDATE_DASHBOARD_SUCCESS = 'UPDATE_DASHBOARD_SUCCESS';
export const UPDATE_DASHBOARD_FAIL = 'UPDATE_DASHBOARD_FAIL';

// DELETE DASHBOARD Constants
export const DELETE_DASHBOARD_REQUEST = 'DELETE_DASHBOARD_REQUEST';
export const DELETE_DASHBOARD_SUCCESS = 'DELETE_DASHBOARD_SUCCESS';
export const DELETE_DASHBOARD_FAIL = 'DELETE_DASHBOARD_FAIL';

